In [31]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [33]:
applications = pd.read_csv("applications_clean.csv")
candidates = pd.read_csv("candidates_clean.csv")
companies  = pd.read_csv("companies_clean.csv")
interviews = pd.read_csv("interviews_clean.csv")
jobs      = pd.read_csv("jobs_clean.csv")
offers    = pd.read_csv("offers_clean.csv")

## Completeness

In [35]:
print(candidates.isna().sum())
print(jobs.isna().sum())
print(applications.isna().sum())
print(interviews.isna().sum())
print(offers.isna().sum())
print(companies.isna().sum())

candidate_id         0
candidate_name       0
years_experience     0
current_city         0
top_skill_area       0
summary              0
experience_bucket    0
dtype: int64
job_id               0
company_id           0
posted_at            0
title                0
role_family          0
level                0
location_type        0
employment_type      0
salary_low           0
salary_high          0
status               0
salary_midpoint      0
posted_date          0
posted_month         0
posted_year          0
posted_month_year    0
salary_range         0
dtype: int64
application_id            0
job_id                    0
candidate_id              0
applied_at                0
source                    0
stage                     0
score                     0
application_date          0
application_month         0
application_year          0
application_month_year    0
dtype: int64
interview_id      0
application_id    0
round_name        0
scheduled_at      0
result            0
dtype: int64
offer_id               0
application_id         0
offered_at             0
base_salary            0
accepted               0
accepted_at          239
acceptance_status      0
dtype: int64
company_id      0
company_name    0
industry        0
company_size    0
hq_city         0
dtype: int64

## Duplicate check

In [40]:
print(candidates.duplicated().sum())
print(jobs.duplicated().sum())
print(applications.duplicated().sum())
print(interviews.duplicated().sum())
print(offers.duplicated().sum())
print(companies.duplicated().sum())

0
0
0
0
0
0

## checking primary key is unique

In [45]:
print(candidates['candidate_id'].duplicated().sum())
print(jobs['job_id'].duplicated().sum())
print(applications['application_id'].duplicated().sum())
print(interviews['interview_id'].duplicated().sum())
print(offers['offer_id'].duplicated().sum())
print(companies['company_id'].duplicated().sum())

0
0
0
0
0
0

## Referential Integrity
**Referential integrity is a rule in a database that ensures relationships between tables remain valid and consistent**

In [53]:
applications['candidate_id'].isin(
    candidates['candidate_id']
).value_counts()

candidate_id
True    15000
Name: count, dtype: int64

In [57]:
applications['job_id'].isin(
    jobs['job_id']
).value_counts()

job_id
True    15000
Name: count, dtype: int64

In [65]:
applications['candidate_id'].isin(candidates['candidate_id']).value_counts()

candidate_id
True    15000
Name: count, dtype: int64

In [71]:
print(interviews.columns.tolist())

['interview_id', 'application_id', 'round_name', 'scheduled_at', 'result']

In [73]:
interviews['application_id'].isin(
    applications['application_id']
).value_counts()

application_id
True    7196
Name: count, dtype: int64

In [75]:
print(offers.columns.tolist())

['offer_id', 'application_id', 'offered_at', 'base_salary', 'accepted', 'accepted_at', 'acceptance_status']

In [77]:
offers['application_id'].isin(
    applications['application_id']
).value_counts()

application_id
True    938
Name: count, dtype: int64

In [79]:
offers[['accepted', 'accepted_at', 'acceptance_status']].head(10)

   accepted          accepted_at acceptance_status
0      True  2025-06-01 01:49:44          Accepted
1      True  2025-02-24 20:46:02          Accepted
2     False                  NaN      Not Accepted
3      True  2025-06-02 06:18:41          Accepted
4      True  2026-01-07 10:31:40          Accepted
5      True  2024-04-04 19:22:44          Accepted
6      True  2025-07-03 12:26:08          Accepted
7      True  2025-12-10 22:42:07          Accepted
8      True  2024-12-03 21:01:11          Accepted
9      True  2024-02-25 10:50:13          Accepted

In [85]:
offers['base_salary'].describe()

count       938.000000
mean     129879.686567
std       35859.026407
min       61321.000000
25%      101857.000000
50%      126487.500000
75%      150348.500000
max      240017.000000
Name: base_salary, dtype: float64

In [87]:
validation_summary = {
    'candidate_id_duplicates': candidates['candidate_id'].duplicated().sum(),
    'job_id_duplicates': jobs['job_id'].duplicated().sum(),
    'application_id_duplicates': applications['application_id'].duplicated().sum(),
    'interview_id_duplicates': interviews['interview_id'].duplicated().sum(),
    'offer_id_duplicates': offers['offer_id'].duplicated().sum(),
    'company_id_duplicates': companies['company_id'].duplicated().sum()
}

print(validation_summary)

{'candidate_id_duplicates': 0, 'job_id_duplicates': 0, 'application_id_duplicates': 0, 'interview_id_duplicates': 0, 'offer_id_duplicates': 0, 'company_id_duplicates': 0}

In [89]:
print(
    'Invalid candidate IDs:',
    (~applications['candidate_id'].isin(candidates['candidate_id'])).sum()
)

print(
    'Invalid job IDs:',
    (~applications['job_id'].isin(jobs['job_id'])).sum()
)

print(
    'Invalid interview application IDs:',
    (~interviews['application_id'].isin(applications['application_id'])).sum()
)

print(
    'Invalid offer application IDs:',
    (~offers['application_id'].isin(applications['application_id'])).sum()
)

Invalid candidate IDs: 0
Invalid job IDs: 0
Invalid interview application IDs: 0
Invalid offer application IDs: 0

In [91]:
print(candidates.columns.tolist())
print(jobs.columns.tolist())
print(applications.columns.tolist())
print(interviews.columns.tolist())
print(offers.columns.tolist())
print(companies.columns.tolist())

['candidate_id', 'candidate_name', 'years_experience', 'current_city', 'top_skill_area', 'summary', 'experience_bucket']
['job_id', 'company_id', 'posted_at', 'title', 'role_family', 'level', 'location_type', 'employment_type', 'salary_low', 'salary_high', 'status', 'salary_midpoint', 'posted_date', 'posted_month', 'posted_year', 'posted_month_year', 'salary_range']
['application_id', 'job_id', 'candidate_id', 'applied_at', 'source', 'stage', 'score', 'application_date', 'application_month', 'application_year', 'application_month_year']
['interview_id', 'application_id', 'round_name', 'scheduled_at', 'result']
['offer_id', 'application_id', 'offered_at', 'base_salary', 'accepted', 'accepted_at', 'acceptance_status']
['company_id', 'company_name', 'industry', 'company_size', 'hq_city']

In [93]:
print(candidates.dtypes)
print(jobs.dtypes)
print(applications.dtypes)
print(interviews.dtypes)
print(offers.dtypes)
print(companies.dtypes)

candidate_id          int64
candidate_name       object
years_experience      int64
current_city         object
top_skill_area       object
summary              object
experience_bucket    object
dtype: object
job_id                 int64
company_id             int64
posted_at             object
title                 object
role_family           object
level                 object
location_type         object
employment_type       object
salary_low             int64
salary_high            int64
status                object
salary_midpoint      float64
posted_date           object
posted_month           int64
posted_year            int64
posted_month_year     object
salary_range           int64
dtype: object
application_id              int64
job_id                      int64
candidate_id                int64
applied_at                 object
source                     object
stage                      object
score                     float64
application_date           object
application_month           int64
application_year            int64
application_month_year     object
dtype: object
interview_id       int64
application_id     int64
round_name        object
scheduled_at      object
result            object
dtype: object
offer_id              int64
application_id        int64
offered_at           object
base_salary           int64
accepted               bool
accepted_at          object
acceptance_status    object
dtype: object
company_id       int64
company_name    object
industry        object
company_size    object
hq_city         object
dtype: object

In [95]:
jobs['salary_range'].head(10)

0    17000
1    16000
2    14000
3    23000
4    21000
5    18000
6    12000
7    37000
8    37000
9    30000
Name: salary_range, dtype: int64

In [97]:
jobs[['salary_low', 'salary_high', 'salary_midpoint', 'salary_range']].head(10)

   salary_low  salary_high  salary_midpoint  salary_range
0      109000       126000         117500.0         17000
1       66000        82000          74000.0         16000
2       92000       106000          99000.0         14000
3       88000       111000          99500.0         23000
4       90000       111000         100500.0         21000
5       87000       105000          96000.0         18000
6       90000       102000          96000.0         12000
7      149000       186000         167500.0         37000
8      194000       231000         212500.0         37000
9      101000       131000         116000.0         30000

In [99]:
jobs[['posted_at', 'posted_date']].head()

             posted_at posted_date
0  2024-01-01 08:36:25  2024-01-01
1  2024-01-01 13:30:59  2024-01-01
2  2024-01-01 18:21:00  2024-01-01
3  2024-01-01 20:39:45  2024-01-01
4  2024-01-02 10:50:13  2024-01-02

In [101]:
applications[['applied_at', 'application_date']].head()

            applied_at application_date
0  2025-10-22 22:54:51       2025-10-22
1  2025-07-18 01:17:20       2025-07-18
2  2026-01-06 18:49:32       2026-01-06
3  2025-10-09 01:22:15       2025-10-09
4  2025-11-16 03:14:55       2025-11-16

In [103]:
applications[['applied_at', 'application_date']].head()

            applied_at application_date
0  2025-10-22 22:54:51       2025-10-22
1  2025-07-18 01:17:20       2025-07-18
2  2026-01-06 18:49:32       2026-01-06
3  2025-10-09 01:22:15       2025-10-09
4  2025-11-16 03:14:55       2025-11-16

In [105]:
interviews['scheduled_at'].head()

0    2025-07-31 01:17:20
1    2025-08-10 01:17:20
2    2025-08-07 01:17:20
3    2025-10-19 01:22:15
4    2025-05-28 01:49:44
Name: scheduled_at, dtype: object

In [107]:
offers[['offered_at', 'accepted_at']].head()

            offered_at          accepted_at
0  2025-06-24 01:49:44  2025-06-01 01:49:44
1  2025-01-31 20:46:02  2025-02-24 20:46:02
2  2024-12-01 02:55:22                  NaN
3  2025-05-27 06:18:41  2025-06-02 06:18:41
4  2026-01-03 10:31:40  2026-01-07 10:31:40